// SURVIVOR
export const FETCH_SURVIVORS_START = 'FETCH_SURVIVORS_START';
export const FETCH_SURVIVORS_SUCCESS = 'FETCH_SURVIVORS_SUCCESS';
export const FETCH_SURVIVORS_FAIL = 'FETCH_SURVIVORS_FAIL';

export const ADD_SURVIVOR_START = 'ADD_SURVIVOR_START';
export const ADD_SURVIVOR_SUCCESS = 'ADD_SURVIVOR_SUCCESS';
export const ADD_SURVIVOR_FAIL = 'ADD_SURVIVOR_FAIL';

export const UPDATE_SURVIVOR_START = 'UPDATE_SURVIVOR_START';
export const UPDATE_SURVIVOR_SUCCESS = 'UPDATE_SURVIVOR_SUCCESS';
export const UPDATE_SURVIVOR_FAIL = 'UPDATE_SURVIVOR_FAIL';

export const INIT_SURVIVOR_START = 'INIT_SURVIVOR_START';
export const INIT_SURVIVOR_SUCCESS = 'INIT_SURVIVOR_SUCCESS';
export const INIT_SURVIVOR_FAIL = 'INIT_SURVIVOR_FAIL';

export const FETCH_SURVIVOR_REPORTS_START = 'FETCH_SURVIVOR_REPORTS_START';
export const FETCH_SURVIVOR_REPORTS_SUCCESS = 'FETCH_SURVIVOR_REPORTS_SUCCESS';
export const FETCH_SURVIVOR_REPORTS_FAIL = 'FETCH_SURVIVOR_REPORTS_FAIL';

// FLAG
export const FLAG_SURVIVOR_START = 'FLAG_SURVIVOR_START';
export const FLAG_SURVIVOR_SUCCESS = 'FLAG_SURVIVOR_SUCCESS';
export const FLAG_SURVIVOR_FAIL = 'FLAG_SURVIVOR_FAIL';
export const FLAG_SURVIVOR_RESET = 'FLAG_SURVIVOR_RESET';

// TRADE
export const TRADE_ITEMS_START = 'TRADE_ITEMS_START';
export const TRADE_ITEMS_SUCCESS = 'TRADE_ITEMS_SUCCESS';
export const TRADE_ITEMS_FAIL = 'TRADE_ITEMS_FAIL';

// REPORTS
export const FETCH_INFECTED_START = 'FETCH_INFECTED_START';
export const FETCH_INFECTED_SUCCESS = 'FETCH_INFECTED_SUCCESS';
export const FETCH_INFECTED_FAIL = 'FETCH_INFECTED_FAIL';

export const FETCH_NON_INFECTED_START = 'FETCH_NON_INFECTED_START';
export const FETCH_NON_INFECTED_SUCCESS = 'FETCH_NON_INFECTED_SUCCESS';
export const FETCH_NON_INFECTED_FAIL = 'FETCH_NON_INFECTED_FAIL';

export const FETCH_INVENTORY_START = 'FETCH_INVENTORY_START';
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS';
export const FETCH_INVENTORY_FAIL = 'FETCH_INVENTORY_FAIL';

export const FETCH_LOST_POINTS_START = 'FETCH_LOST_POINTS_START';
export const FETCH_LOST_POINTS_SUCCESS = 'FETCH_LOST_POINTS_SUCCESS';
export const FETCH_LOST_POINTS_FAIL = 'FETCH_LOST_POINTS_FAIL';
