export const FETCH_SURVIVORS_START = 'FETCH_SURVIVORS_START';
export const FETCH_SURVIVORS_SUCCESS = 'FETCH_SURVIVORS_SUCCESS';
export const FETCH_SURVIVORS_FAIL = 'FETCH_SURVIVORS_FAIL';

export const ADD_SURVIVOR_START = 'ADD_SURVIVOR_START';
export const ADD_SURVIVOR_SUCCESS = 'ADD_SURVIVOR_SUCCESS';
export const ADD_SURVIVOR_FAIL = 'ADD_SURVIVOR_FAIL';

export const UPDATE_SURVIVOR_START = 'UPDATE_SURVIVOR_START';
export const UPDATE_SURVIVOR_SUCCESS = 'UPDATE_SURVIVOR_SUCCESS';
export const UPDATE_SURVIVOR_FAIL = 'UPDATE_SURVIVOR_FAIL';

export const INIT_SURVIVOR_START = 'INIT_SURVIVOR_START';
export const INIT_SURVIVOR_SUCCESS = 'INIT_SURVIVOR_SUCCESS';
export const INIT_SURVIVOR_FAIL = 'INIT_SURVIVOR_FAIL';

export const FLAG_SURVIVOR_START = 'FLAG_SURVIVOR_START';
export const FLAG_SURVIVOR_SUCCESS = 'FLAG_SURVIVOR_SUCCESS';
export const FLAG_SURVIVOR_FAIL = 'FLAG_SURVIVOR_FAIL';

export const FETCH_SURVIVOR_REPORTS_START = 'FETCH_SURVIVOR_REPORTS_START';
export const FETCH_SURVIVOR_REPORTS_SUCCESS = 'FETCH_SURVIVOR_REPORTS_SUCCESS';
export const FETCH_SURVIVOR_REPORTS_FAIL = 'FETCH_SURVIVOR_REPORTS_FAIL';
