export const ADD_SURVIVOR_START = 'ADD_SURVIVOR_START';
export const ADD_SURVIVOR_SUCCESS = 'ADD_SURVIVOR_SUCCESS';
export const ADD_SURVIVOR_FAIL = 'ADD_SURVIVOR_FAIL';

export const INIT_SURVIVOR_START = 'INIT_SURVIVOR_START';
export const INIT_SURVIVOR_SUCCESS = 'INIT_SURVIVOR_SUCCESS';
export const INIT_SURVIVOR_FAIL = 'INIT_SURVIVOR_FAIL';
